name: worldsibubpe-devnetyzz
version: "1.0"

client:
  organization: worldsibubpe-devnetyzz

  # If you have an MSP folder, update this path.
  # Otherwise, leave it as it is
  # The msp folder contains multiple folders,
  # two of those are keystore and signcerts
  credentialStore:
    path: ../config
    cryptoStore:
      path: ../config

channels:
  public:
    orderers:
      - orderer1.devnetaxl-ordererftryf.svc.cluster.local
    peers:
      peer1.worldsibubpe-devnetyzz.svc.cluster.local:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.govgqy-devnetyuc.svc.cluster.local:
        endorsingPeer: true
        chaincodeQuery: false
        ledgerQuery: false
        eventSource: false

organizations:
  worldsibubpe-devnetyzz:
    mspid: worldsibubpe-devnetyzzMSP
    peers: 
      - peer1.worldsibubpe-devnetyzz.svc.cluster.local
    certificateAuthorities:
      - ica.worldsibubpe-devnetyzz.svc.cluster.local
  govgqy-devnetyuc:
    mspid: govgqy-devnetyucMSP
    peers: 
      - peer1.govgqy-devnetyuc.svc.cluster.local
    certificateAuthorities:
      - ica.govgqy-devnetyuc.svc.cluster.local

orderers:
  orderer1.devnetaxl-ordererftryf.svc.cluster.local:
    url: grpcs://c-prod001.worldsibu.com:30704
    grpcOptions:
      ssl-target-name-override: orderer1.devnetaxl-ordererftryf.svc.cluster.local
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICYzCCAgqgAwIBAgIULgwXHhhqDj1Z3mnPC4ltLk3xfz8wCgYIKoZIzj0EAwIw
        gYQxCzAJBgNVBAYTAlVTMRcwFQYDVQQIEw5Ob3J0aCBDYXJvbGluYTEUMBIGA1UE
        ChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZhYnJpYzE1MDMGA1UEAxMscmNhLmRl
        dm5ldGF4bC1vcmRlcmVyZnRyeWYuc3ZjLmNsdXN0ZXIubG9jYWwwHhcNMTkwNjAy
        MjA0NTAwWhcNMjQwNTMxMjA1MDAwWjB3MQswCQYDVQQGEwJVUzEXMBUGA1UECBMO
        Tm9ydGggQ2Fyb2xpbmExFDASBgNVBAoTC0h5cGVybGVkZ2VyMQ8wDQYDVQQLEwZj
        bGllbnQxKDAmBgNVBAMTH2Rldm5ldGF4bC1vcmRlcmVyZnRyeWYtUkNBYWRtaW4w
        WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARE0q7AkCxztvfJRt1EuAOuAZ1skyZP
        h580kfcyF42PRqiV/lxQEjBIDX7yK7ZHpQWoRSa2YS/a3Hvo5WkNh3mUo2YwZDAO
        BgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQU5azs
        6mTCyYQ4XMx84WtHIRTOJ9IwHwYDVR0jBBgwFoAUDb3DBTGn6VWJ8WHQ2eNSpyzm
        fvkwCgYIKoZIzj0EAwIDRwAwRAIgTECD5xi3PiLxX+1/r8/FR39PweoMbcxpsssl
        Jvga/poCIDFt1B+YGH8moMMHNPj9tF3cNXzd8+OWx3NSOMm8+iGx
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIICUTCCAfegAwIBAgIUK2ewrQuGWTo+5iE45BBRnqfvd6QwCgYIKoZIzj0EAwIw
        gYQxCzAJBgNVBAYTAlVTMRcwFQYDVQQIEw5Ob3J0aCBDYXJvbGluYTEUMBIGA1UE
        ChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZhYnJpYzE1MDMGA1UEAxMscmNhLmRl
        dm5ldGF4bC1vcmRlcmVyZnRyeWYuc3ZjLmNsdXN0ZXIubG9jYWwwHhcNMTkwNjAy
        MjA0NTAwWhcNMzQwNTI5MjA0NTAwWjCBhDELMAkGA1UEBhMCVVMxFzAVBgNVBAgT
        Dk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBlcmxlZGdlcjEPMA0GA1UECxMG
        RmFicmljMTUwMwYDVQQDEyxyY2EuZGV2bmV0YXhsLW9yZGVyZXJmdHJ5Zi5zdmMu
        Y2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABMcSuPg/DS20
        SztK/+tCrOI0CdUH9XnmIsdYgUPkqJgBZudgRED8xulDHaJZun+fbVADexzSZho0
        lX7PUKqtteCjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEB
        MB0GA1UdDgQWBBQNvcMFMafpVYnxYdDZ41KnLOZ++TAKBggqhkjOPQQDAgNIADBF
        AiEAuiG07gFlzi2bOw7q7Bad0Tfg6PRVZbCBC8JWSJ0uv3wCIFC/pkzqtH0ek+7b
        pvnWL/nSh4ItaoKzOpAcjrcEYUkw
        -----END CERTIFICATE-----
        

peers:
  peer1.worldsibubpe-devnetyzz.svc.cluster.local:
    url: grpcs://c-prod001.worldsibu.com:30686
    eventUrl: grpcs://c-prod001.worldsibu.com:30688
    grpcOptions:
      ssl-target-name-override: peer1.worldsibubpe-devnetyzz.svc.cluster.local
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICYzCCAgqgAwIBAgIUcRZWImNHa1U/Ybs/lvcgkU9sD58wCgYIKoZIzj0EAwIw
        gYQxCzAJBgNVBAYTAlVTMRcwFQYDVQQIEw5Ob3J0aCBDYXJvbGluYTEUMBIGA1UE
        ChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZhYnJpYzE1MDMGA1UEAxMscmNhLndv
        cmxkc2lidWJwZS1kZXZuZXR5enouc3ZjLmNsdXN0ZXIubG9jYWwwHhcNMTkwNjAy
        MjA0NjAwWhcNMjQwNTMxMjA1MTAwWjB3MQswCQYDVQQGEwJVUzEXMBUGA1UECBMO
        Tm9ydGggQ2Fyb2xpbmExFDASBgNVBAoTC0h5cGVybGVkZ2VyMQ8wDQYDVQQLEwZj
        bGllbnQxKDAmBgNVBAMTH3dvcmxkc2lidWJwZS1kZXZuZXR5enotUkNBYWRtaW4w
        WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQu9x1lS+OehifJXhvrUV4YwVBmGbN2
        +oXV/rFmVvthwxyMgh1/luHZWRUU8RSC6IKRfXnduMR6olBGBJGBGW/ho2YwZDAO
        BgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQURWRi
        J4O4x6wbIMZR8SFJxLJmSe0wHwYDVR0jBBgwFoAUh4xsjcsNKS3T5BKvxRJ4Znw8
        sYEwCgYIKoZIzj0EAwIDRwAwRAIgJmkZwEcXWn9PiuP7g1AChWZnxOxScyXU9vV3
        m39XWesCIHT2ueNFW6hDG3jyjJGefz8lONGvsV4OHim4PN8T/YoG
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIICUTCCAfegAwIBAgIUVUC5vYqz9S5z2PCuTKP8nwHSf/wwCgYIKoZIzj0EAwIw
        gYQxCzAJBgNVBAYTAlVTMRcwFQYDVQQIEw5Ob3J0aCBDYXJvbGluYTEUMBIGA1UE
        ChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZhYnJpYzE1MDMGA1UEAxMscmNhLndv
        cmxkc2lidWJwZS1kZXZuZXR5enouc3ZjLmNsdXN0ZXIubG9jYWwwHhcNMTkwNjAy
        MjA0NTAwWhcNMzQwNTI5MjA0NTAwWjCBhDELMAkGA1UEBhMCVVMxFzAVBgNVBAgT
        Dk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBlcmxlZGdlcjEPMA0GA1UECxMG
        RmFicmljMTUwMwYDVQQDEyxyY2Eud29ybGRzaWJ1YnBlLWRldm5ldHl6ei5zdmMu
        Y2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDJxZMgvlhG7
        EOgh1xyA1oJBs5cjCjR4YIHsKNzi9mMwj0HUMH3Jru+mFjiq1DAJkm4ipoNU4C3K
        FwphX+Zsk3CjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEB
        MB0GA1UdDgQWBBSHjGyNyw0pLdPkEq/FEnhmfDyxgTAKBggqhkjOPQQDAgNIADBF
        AiEA78ji/9l6VQMONrjBaLDrGtDgNZdui6xBtQBEN2+iztQCIFRfcdJv/2yfGLqI
        mjVeupQJ2y7C/zGCQqvq88mfNhDR
        -----END CERTIFICATE-----
        
  peer1.govgqy-devnetyuc.svc.cluster.local:
    url: grpcs://c-prod001.worldsibu.com:30693
    eventUrl: grpcs://c-prod001.worldsibu.com:30695
    grpcOptions:
      ssl-target-name-override: peer1.govgqy-devnetyuc.svc.cluster.local
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICVjCCAf2gAwIBAgIUU1oEuTkKerKR3wzAg3KP05sO0/UwCgYIKoZIzj0EAwIw
        fjELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
        EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMS8wLQYDVQQDEyZyY2EuZ292
        Z3F5LWRldm5ldHl1Yy5zdmMuY2x1c3Rlci5sb2NhbDAeFw0xOTA2MDIyMDQ3MDBa
        Fw0yNDA1MzEyMDUyMDBaMHExCzAJBgNVBAYTAlVTMRcwFQYDVQQIEw5Ob3J0aCBD
        YXJvbGluYTEUMBIGA1UEChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBmNsaWVudDEi
        MCAGA1UEAxMZZ292Z3F5LWRldm5ldHl1Yy1SQ0FhZG1pbjBZMBMGByqGSM49AgEG
        CCqGSM49AwEHA0IABHR4dROoJ+srHCJTxreEODHrDw//vSEJ4hvztjicQFXw0Y6p
        MM2jXOjYLwx8zJb2BakyGx1w9TPkwJZU2xxoZYajZjBkMA4GA1UdDwEB/wQEAwIB
        BjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBQA38DaxFUMteBb/r90tKi2
        blwXTjAfBgNVHSMEGDAWgBQUWYjSc8CFTsUoYVE3hzleob4dIjAKBggqhkjOPQQD
        AgNHADBEAiA9YERNla77gIsesdtb/wOUp+qFBpRb78YuXJ6XI7+2mgIgdmE7e9S3
        rPLjj6XVh5QBNDKUgcNswI/WGJu/HV4z3sU=
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIICQTCCAeigAwIBAgITJOOEffrKgUEpKOtE7DK2t8f4JjAKBggqhkjOPQQDAjB+
        MQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExFDASBgNVBAoT
        C0h5cGVybGVkZ2VyMQ8wDQYDVQQLEwZGYWJyaWMxLzAtBgNVBAMTJnJjYS5nb3Zn
        cXktZGV2bmV0eXVjLnN2Yy5jbHVzdGVyLmxvY2FsMB4XDTE5MDYwMjIwNDYwMFoX
        DTM0MDUyOTIwNDYwMFowfjELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENh
        cm9saW5hMRQwEgYDVQQKEwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMS8w
        LQYDVQQDEyZyY2EuZ292Z3F5LWRldm5ldHl1Yy5zdmMuY2x1c3Rlci5sb2NhbDBZ
        MBMGByqGSM49AgEGCCqGSM49AwEHA0IABOJt1avM1/Sxavkhdjg8YEAowzBsn8bv
        8M3vBZVg5aBAltmmviMRCUBXpekGAkdpQNKw2amtiZKuZVR5ov8C6bWjRTBDMA4G
        A1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBQUWYjS
        c8CFTsUoYVE3hzleob4dIjAKBggqhkjOPQQDAgNHADBEAiAuFLkIDckeqK0qUPZ6
        Cpp/VcKFFDdZ2K/J+OIIJwlFpgIgW3MaZY966oMtkWCoukgdr4XTolz7p//V1Cz4
        Bfgxtak=
        -----END CERTIFICATE-----
        

certificateAuthorities:
  ica.worldsibubpe-devnetyzz.svc.cluster.local:
    caName: ica.worldsibubpe-devnetyzz.svc.cluster.local
    url: https://c-prod001.worldsibu.com:30681
    httpOptions:
      verify: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICYzCCAgqgAwIBAgIUcRZWImNHa1U/Ybs/lvcgkU9sD58wCgYIKoZIzj0EAwIw
        gYQxCzAJBgNVBAYTAlVTMRcwFQYDVQQIEw5Ob3J0aCBDYXJvbGluYTEUMBIGA1UE
        ChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZhYnJpYzE1MDMGA1UEAxMscmNhLndv
        cmxkc2lidWJwZS1kZXZuZXR5enouc3ZjLmNsdXN0ZXIubG9jYWwwHhcNMTkwNjAy
        MjA0NjAwWhcNMjQwNTMxMjA1MTAwWjB3MQswCQYDVQQGEwJVUzEXMBUGA1UECBMO
        Tm9ydGggQ2Fyb2xpbmExFDASBgNVBAoTC0h5cGVybGVkZ2VyMQ8wDQYDVQQLEwZj
        bGllbnQxKDAmBgNVBAMTH3dvcmxkc2lidWJwZS1kZXZuZXR5enotUkNBYWRtaW4w
        WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQu9x1lS+OehifJXhvrUV4YwVBmGbN2
        +oXV/rFmVvthwxyMgh1/luHZWRUU8RSC6IKRfXnduMR6olBGBJGBGW/ho2YwZDAO
        BgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQURWRi
        J4O4x6wbIMZR8SFJxLJmSe0wHwYDVR0jBBgwFoAUh4xsjcsNKS3T5BKvxRJ4Znw8
        sYEwCgYIKoZIzj0EAwIDRwAwRAIgJmkZwEcXWn9PiuP7g1AChWZnxOxScyXU9vV3
        m39XWesCIHT2ueNFW6hDG3jyjJGefz8lONGvsV4OHim4PN8T/YoG
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIICUTCCAfegAwIBAgIUVUC5vYqz9S5z2PCuTKP8nwHSf/wwCgYIKoZIzj0EAwIw
        gYQxCzAJBgNVBAYTAlVTMRcwFQYDVQQIEw5Ob3J0aCBDYXJvbGluYTEUMBIGA1UE
        ChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZhYnJpYzE1MDMGA1UEAxMscmNhLndv
        cmxkc2lidWJwZS1kZXZuZXR5enouc3ZjLmNsdXN0ZXIubG9jYWwwHhcNMTkwNjAy
        MjA0NTAwWhcNMzQwNTI5MjA0NTAwWjCBhDELMAkGA1UEBhMCVVMxFzAVBgNVBAgT
        Dk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBlcmxlZGdlcjEPMA0GA1UECxMG
        RmFicmljMTUwMwYDVQQDEyxyY2Eud29ybGRzaWJ1YnBlLWRldm5ldHl6ei5zdmMu
        Y2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDJxZMgvlhG7
        EOgh1xyA1oJBs5cjCjR4YIHsKNzi9mMwj0HUMH3Jru+mFjiq1DAJkm4ipoNU4C3K
        FwphX+Zsk3CjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEB
        MB0GA1UdDgQWBBSHjGyNyw0pLdPkEq/FEnhmfDyxgTAKBggqhkjOPQQDAgNIADBF
        AiEA78ji/9l6VQMONrjBaLDrGtDgNZdui6xBtQBEN2+iztQCIFRfcdJv/2yfGLqI
        mjVeupQJ2y7C/zGCQqvq88mfNhDR
        -----END CERTIFICATE-----
        
  ica.govgqy-devnetyuc.svc.cluster.local:
    caName: ica.govgqy-devnetyuc.svc.cluster.local
    url: https://c-prod001.worldsibu.com:30685
    httpOptions:
      verify: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICVjCCAf2gAwIBAgIUU1oEuTkKerKR3wzAg3KP05sO0/UwCgYIKoZIzj0EAwIw
        fjELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
        EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMS8wLQYDVQQDEyZyY2EuZ292
        Z3F5LWRldm5ldHl1Yy5zdmMuY2x1c3Rlci5sb2NhbDAeFw0xOTA2MDIyMDQ3MDBa
        Fw0yNDA1MzEyMDUyMDBaMHExCzAJBgNVBAYTAlVTMRcwFQYDVQQIEw5Ob3J0aCBD
        YXJvbGluYTEUMBIGA1UEChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBmNsaWVudDEi
        MCAGA1UEAxMZZ292Z3F5LWRldm5ldHl1Yy1SQ0FhZG1pbjBZMBMGByqGSM49AgEG
        CCqGSM49AwEHA0IABHR4dROoJ+srHCJTxreEODHrDw//vSEJ4hvztjicQFXw0Y6p
        MM2jXOjYLwx8zJb2BakyGx1w9TPkwJZU2xxoZYajZjBkMA4GA1UdDwEB/wQEAwIB
        BjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBQA38DaxFUMteBb/r90tKi2
        blwXTjAfBgNVHSMEGDAWgBQUWYjSc8CFTsUoYVE3hzleob4dIjAKBggqhkjOPQQD
        AgNHADBEAiA9YERNla77gIsesdtb/wOUp+qFBpRb78YuXJ6XI7+2mgIgdmE7e9S3
        rPLjj6XVh5QBNDKUgcNswI/WGJu/HV4z3sU=
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIICQTCCAeigAwIBAgITJOOEffrKgUEpKOtE7DK2t8f4JjAKBggqhkjOPQQDAjB+
        MQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExFDASBgNVBAoT
        C0h5cGVybGVkZ2VyMQ8wDQYDVQQLEwZGYWJyaWMxLzAtBgNVBAMTJnJjYS5nb3Zn
        cXktZGV2bmV0eXVjLnN2Yy5jbHVzdGVyLmxvY2FsMB4XDTE5MDYwMjIwNDYwMFoX
        DTM0MDUyOTIwNDYwMFowfjELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENh
        cm9saW5hMRQwEgYDVQQKEwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMS8w
        LQYDVQQDEyZyY2EuZ292Z3F5LWRldm5ldHl1Yy5zdmMuY2x1c3Rlci5sb2NhbDBZ
        MBMGByqGSM49AgEGCCqGSM49AwEHA0IABOJt1avM1/Sxavkhdjg8YEAowzBsn8bv
        8M3vBZVg5aBAltmmviMRCUBXpekGAkdpQNKw2amtiZKuZVR5ov8C6bWjRTBDMA4G
        A1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBQUWYjS
        c8CFTsUoYVE3hzleob4dIjAKBggqhkjOPQQDAgNHADBEAiAuFLkIDckeqK0qUPZ6
        Cpp/VcKFFDdZ2K/J+OIIJwlFpgIgW3MaZY966oMtkWCoukgdr4XTolz7p//V1Cz4
        Bfgxtak=
        -----END CERTIFICATE-----
        
  